site_name: Documentation for Tape-out Templates
site_url: https://bwoah-kimi.github.io/Tape-out_template_doc/
site_author: Bwoah-Kimi

theme:
  name: material
  language: zh
  font:
    code: JetBrainsMono
  features:
    - navigation.instant

markdown_extensions:
  - codehilite

extra_css:
  - css/custom.css

plugins:
  - search:
      lang:
        - zh
        - en

nav:
  - Overview: index.md
  - Submodule Behavioral Simulation: 1_submodule_behavioral_simulation.md
  - Submodule Synthesis: 2_submodule_synthesis.md
  - Submodule Gate Level Simulation: 3_submodule_gate_level_simulation.md
  - Submodule Place & Route: 4_submodule_implementation.md
  - IO Module: 5_io.md
