site_name: Documentation for Tape-out
site_url: https://bwoah-kimi.github.io/Tape-out_template_doc/
site_author: Bwoah-Kimi
copyright: Copyright &copy; 2024 School of Intergrated Circuits, Peking University

repo_url: https://github.com/Bwoah-Kimi/Tape-out_template_doc
repo_name: Source Code
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  logo: figs/pku_logo.png
  favicon: figs/pku_logo_red.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrainsMono
  features:
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.action.view
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search:
      lang:
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Bwoah-Kimi/Tape-out_template_doc
      branch: main
      token: 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
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true

extra_css:
  - extra.css

nav:
  - Welcome to Tape-out Docs!: index.md
  - I. EDA Tools & Environment: 0_eda.md
  - II. Frontend:
    - 1. Submodule Behavioral Simulation: 1_submodule_behavioral_simulation.md
    - 2. Submodule Synthesis: 2_submodule_synthesis.md
    - 3. Submodule Gate Level Simulation: 3_submodule_gate_level_simulation.md
  - III. Backend:
    - 4. Submodule Implementation: 4_submodule_implementation.md
    - 5. TOP IO Implementation: 5_io.md
    - 6. DRC/LVS: 6_lvs_drc.md
    - 7. Tape-out: 7_final_layout.md
  - IV. Post-tapeout:
    - 8. PCB: 8_PCB.md
    - 9. Packaging: 9_package.md
    - 10. Testing: 10_testing.md
