site_name: Documentation for Tape-out
site_url: https://bwoah-kimi.github.io/Tape-out_template_doc/
site_author: Bwoah-Kimi
copyright: Copyright &copy; 2024-2025 School of Integrated Circuits, Peking University

repo_url: https://github.com/Bwoah-Kimi/Tape-out_template_doc
repo_name: GitHub Repo
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  logo: assets/brand/pku_logo.png
  favicon: assets/brand/pku_logo_red.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/refresh-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  font:
    code: JetBrainsMono
  features:
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.action.view
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex

plugins:
  - search:
      lang:
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Bwoah-Kimi/Tape-out_template_doc
      branch: main
      token: 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
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
  - encryptcontent:
      global_password: 'coICRGGm5sY9OyztWam0Q2n+tjwb++kv3J9qXAEx5vc=' # jialab-tapeout Base64 encoded
      password_button: True
      password_button_text: 'ENTER'
      encryption_info_message: 'Contact your administrator for access to this page.'
      decryption_failure_message: 'Invalid password.'
      remember_keys: true
      remember_password: true
      title_prefix: ''

extra_css:
  - extra.css

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - Welcome to Tape-out Docs!: index.md
  - I. EDA Tools & Environment: background/eda_tools_environment.md
  - II. Frontend:
    - 1. RTL Design:
      - 1.1 SRAM IP Specification: frontend/rtl_design/sram_ip_spec.md
      - 1.2 FPU IP Specification: frontend/rtl_design/fpu_ip_spec.md
      - 1.3 System Integration: frontend/rtl_design/system_integration.md
    - 2. Simulation: frontend/simulation.md
    - 3. Submodule Synthesis:
      - 3.1 TSMC N22 Synthesis: frontend/submodule_synthesis_22nm.md
      - 3.2 TSMC N12 Synthesis: frontend/submodule_synthesis_12nm.md
  - III. Backend:
    - 1. Submodule Physical Implementation:
      - 1.1 TSMC N22 Implementation: backend/submodule_implementation_22nm.md
      - 1.2 TSMC N12 Implementation: backend/submodule_implementation_12nm.md
    - 2. TOP IO Implementation:
      - 2.1 TSMC N22 Implementation: backend/top_io_implementation_22nm.md
      - 2.2 TSMC N12 Implementation: backend/top_io_implementation_12nm.md
    - 3. Physical Verification:
      - 3.1 Block-Level Verification: backend/lvs_drc_block.md
      - 3.2 Top-Level Verification: backend/lvs_drc_top.md
    - 4. Tape-out: backend/final_layout.md
  - IV. Post-tapeout:
    - 1. PCB: post_tapeout/pcb.md
    - 2. Packaging: post_tapeout/package.md
    - 3. Testing: post_tapeout/testing.md
  - V. Appendix:
    - 1. RISC-V CPU Debugging: appendix/cpu_debug.md
    - 2. C Compiling: appendix/c_compiling.md
    - 3. WSL: appendix/wsl.md
    - 4. FPGA Verification: appendix/fpga_verification.md
    - 5. PDK Setup: appendix/pdk_setup.md
    - 6. Using DRAM on FPGA: appendix/fpga_dram.md
    - 7. STA & Power: appendix/sta_power.md
    - 8. Linux Environment & Common Tools: appendix/linux_environment.md
  - VI. Legacy:
    - 1. Behavioral Simulation (Deprecated): legacy/behavioral_simulation.md
    - 2. Gate-Level Simulation (Deprecated): legacy/gate_level_simulation.md
    - 3. Submodule Synthesis (Deprecated): legacy/submodule_synthesis_deprecated.md
    - 4. Submodule Synthesis (New): legacy/submodule_synthesis_new.md
    - 5. Submodule Implementation (Deprecated): legacy/submodule_implementation_deprecated.md
    - 6. Submodule Implementation (New): legacy/submodule_implementation_new.md
    - 7. Digital-CIM IP Specification (Deprecated): legacy/dcim_ip_spec.md
  - VII. Join Us! How to Contribute?: contribute.md
